### PR TITLE
spacy-pkuseg 1.0.0

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

References:
- includes #20
- (maybe) unblocks https://github.com/conda-forge/spacy-models-feedstock/pull/7

Changes:
- `conda-forge.yml`
  - add `osx-arm64`
  - add bot inspection for future PRs
  - use azure
- `.ci_support`
  - add manual `numpy2` migration
- `meta.yaml`
  - remove all jinja vars except `version`
  - update `pip` and `pytest` invocations
  - remove `cython` runtime dep, per https://github.com/conda-forge/spacy-pkuseg-feedstock/pull/11#issuecomment-1120694041

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/spacy-pkuseg ready for review

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by h-vetinari** [comment]
Thanks @bollwyvl! I'm going to merge this to unblock spacy-models (given how all of that has been blocked for months already), but I'll add `@conda-forge/spacy` here as a maintainer, and if you'd be willing to join that team, that'd be great!

**Pull request merged**
